#!/bin/env bash

#
# Copyright (c) 2022.  NetFoundry Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

preload_dir=$(dirname ${BASH_SOURCE[0]})
preload_lib=${preload_dir}/libzitify.so

usage() {
    echo "zitify <cmd> [args]"
    echo "       Run zitified <cmd>"
    echo ""
    echo "zitify enroll -j <enrollment token> -i <identity file> [ -k|--key <private key> [ -c|--cert certificate ] ]"
    echo "       Enroll identity"
}

function enroll() {
  python - $* <<EOF
import sys
import ctypes
import argparse

zitilib=ctypes.CDLL("${preload_lib}")
enroll=zitilib.Ziti_enroll_identity
enroll.argtypes = [
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_char_p),
        ctypes.POINTER(ctypes.c_size_t)
]
enroll.restype = ctypes.c_int

parser=argparse.ArgumentParser()
parser.add_argument('-j', '--jwt', required=True)
parser.add_argument('-i', '--identity', required=True)
parser.add_argument('-k', '--key', required=False)
parser.add_argument('-c', '--cert', required=False)

args = parser.parse_args()

with open(args.jwt, 'r') as jwt:
    jwtc = jwt.read()
    jwtc = bytes(jwtc, 'utf-8')
    id_json = ctypes.c_char_p()
    id_json_len = ctypes.c_size_t()
    retcode = enroll(jwtc, args.key, args.cert,
                           ctypes.byref(id_json),
                           ctypes.byref(id_json_len))
    if retcode != 0:
         raise RuntimeError('failed to enroll')

    with open(args.identity, 'w') as id_file:
         id_file.write(id_json.value.decode())

EOF
}

if [ -z "$1" ]; then
usage
exit
fi

if [ "$1" == "enroll" ]; then
  enroll "${@:2}"
  exit
fi


LD_PRELOAD=$preload_lib "$@"
