name: C/C++ CI

on:
  workflow_dispatch:
  schedule:
    # run weekly Sun at 5am UTC to keep caches fresh
    - cron: '5 5 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        ziti_version: [ 'v1.6', 'stable' ]
    uses: ./.github/workflows/integration-test.yml
    with:
      ziti_version: ${{ matrix.ziti_version }}
    permissions:
      contents: read
      checks: write

  build:
    needs: test
    name: ${{ matrix.spec.name }}
    runs-on: ${{ matrix.spec.runner }}
    container:
      image: ${{ matrix.spec.builder }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      VCPKG_FEATURE_FLAGS: dependencygraph
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        spec:
          - { name: 'Linux x86_64', runner: 'ubuntu-latest', target: 'linux-x64', builder: 'openziti/ziti-builder:v3'}
          - { name: 'Linux ARM', runner: 'ubuntu-latest', target: 'linux-arm', builder: 'openziti/ziti-builder:v3' }
          - { name: 'Linux ARM64', runner: 'ubuntu-latest', target: 'linux-arm64', builder: 'openziti/ziti-builder:v3' }
          - { name: 'MacOS x86_64', runner: 'macos-15-intel', target: 'macOS-x64' }
          - { name: 'MacOS arm64', runner: 'macos-15', target: 'macOS-arm64' }
          - { name: 'Windows x86_64', runner: 'windows-2025', target: 'windows-x64' }
          - { name: 'Windows x86', runner: 'windows-2025', target: 'windows-x86' }
          - { name: 'Windows ARM64', runner: 'windows-2025', target: 'windows-arm64' }
          - { name: 'Windows ming64', runner: 'windows-2025', target: 'windows-x64-mingw' }
    steps:
      - name: Add msbuild to PATH
        if: startsWith(matrix.spec.runner, 'windows')
        uses: microsoft/setup-msbuild@v3

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: run build for ${{ matrix.spec.target }}
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.spec.target }}

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ziti-prox-c-${{ matrix.spec.target }}
          path: ./build/programs/ziti-prox-c/**/ziti-prox-c*.zip

      - name: upload SDK artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ziti-sdk-${{ matrix.spec.target }}
          path: ./build/package/ziti-sdk-*
