name: CI Test
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - release-*


permissions:
  contents: read

concurrency:
  group: integ-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
      checks: write
    name: ${{ matrix.spec.target }}-test-${{ matrix.ziti_version }}
    runs-on: ${{ matrix.spec.runner }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        ziti_version: [ 'v1.6', 'stable' ]
        spec:
          - { runner: 'ubuntu-latest', target: 'linux-x64' }
          - { runner: 'macos-15-intel', target: 'macOS-x64' }
          - { runner: 'macos-15', target: 'macOS-arm64' }
          - { runner: 'windows-2025', target: 'windows-x64' }
          - { runner: 'windows-2025', target: 'windows-x64-mingw' }
    steps:
      - name: install linux deps
        if: runner.os == 'linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python3-venv autoconf autoconf-archive automake libtool
          
      - name: macOS tools
        if: runner.os == 'macOS'
        uses: gerlero/brew-install@v1
        with:
          packages: autoconf autoconf-archive automake pkg-config libtool

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup build
        shell: bash
        run: |
          CI_CACHE="${GITHUB_WORKSPACE}/.ci.cache"
          VCPKG_BINARY_SOURCES="clear;files,${GITHUB_WORKSPACE}/.ci.cache,readwrite"
          mkdir -p ${CI_CACHE}
          echo "CI_CACHE=${CI_CACHE}" >> $GITHUB_ENV
          echo "VCPKG_BINARY_SOURCES=${VCPKG_BINARY_SOURCES}" >> $GITHUB_ENV

      - uses: openziti/ziti/setup-cli@main
        id: ziti
        with:
          version: ${{ matrix.ziti_version }}

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: './vcpkg.json'

      - uses: actions/cache/restore@v4
        id: restore
        with:
          key: vbc-${{ matrix.spec.target }}-${{ hashFiles('./vcpkg.json', './vcpkg-overlays/**/*') }}
          restore-keys: vbc-${{ matrix.spec.target }}-
          path: ${{ env.CI_CACHE }}

      - name: Configure CMake
        id: configure
        shell: bash
        run: |
          ASAN_ARG=""
          if [[ "${{ runner.os }}" != "Windows" ]]; then
            ASAN_ARG="-Dziti_ASAN=ON"
          fi
          cmake --preset ci-${{ matrix.spec.target }} ${ASAN_ARG} -B ./build

      - uses: actions/cache/save@v4
        with:
          key: ${{ steps.restore.outputs.cache-primary-key }}
          path: ${{ env.CI_CACHE }}

      - name: build CMake
        run: |
          cmake --build ./build
        shell: bash

      - name: test
        working-directory: ./build
        continue-on-error: false
        shell: bash
        run: |
          ctest -C Debug -VV --no-compress-output --timeout 1200

      - name: upload test summary
        if: ${{ !cancelled() }}
        uses: mikepenz/action-junit-report@v6
        with:
          job_summary_text: 'Integration test results for ${{ steps.ziti.outputs.version }}'
          detailed_summary: 'true'
          include_skipped: 'true'
          check_retries: 'true'
          group_suite: 'true'
          report_paths: ${{ github.workspace }}/build/tests/**/TEST-*.xml

      - name: integration tests bundle
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.spec.target }}-${{ steps.ziti.outputs.version }}-integ-testdata
          path: |
            ./build/tests/**/testdata/**/*

